import type { RuleDefinition, FixActionSuggestion, ScmFileExistsParams, ScmAnyOfParams } from './types.js';
import type { EntityRow } from '@forgeportal/catalog';

/** CI file path set for pattern detection */
const CI_PATHS = new Set([
  '.github/workflows/ci.yml',
  '.github/workflows/build.yml',
  '.gitlab-ci.yml',
]);

/** Docs file path set for pattern detection */
const DOCS_PATHS = new Set([
  'docs/index.md',
  'docs/README.md',
]);

/**
 * Returns a fix action suggestion for a failing rule, or null if no fix is available.
 *
 * Resolution order:
 *   1. Rule definition has explicit `fixAction` → use it as-is (author wins)
 *   2. Built-in mapping by rule type + params
 *   3. null — no automated fix available
 */
export function resolveFixAction(
  rule:   RuleDefinition,
  entity: EntityRow,
): FixActionSuggestion | null {
  // 1. Author-specified fix (highest priority)
  if (rule.fixAction) return rule.fixAction;

  const scm           = entity.scm as Record<string, unknown>;
  const provider      = (scm['provider']      as string | undefined) ?? 'github';
  const owner         = (scm['owner']         as string | undefined) ?? '';
  const repo          = (scm['repo']          as string | undefined) ?? '';
  const defaultBranch = (scm['defaultBranch'] as string | undefined) ?? 'main';

  // 2. Built-in mapping
  switch (rule.type) {
    case 'scm.file.exists': {
      const { path } = rule.params as ScmFileExistsParams;
      return buildFileExistsFix(path, { provider, owner, repo, defaultBranch });
    }

    case 'scm.anyOf': {
      const { paths } = rule.params as ScmAnyOfParams;
      const hasCiPath   = paths.some((p) => CI_PATHS.has(p));
      const hasDocsPath = paths.some((p) => DOCS_PATHS.has(p));

      if (hasCiPath) {
        return {
          actionId: 'ci.bootstrap@v1',
          suggestedInputs: {
            provider,
            owner,
            repo,
            type:     provider === 'gitlab' ? 'gitlab-ci' : 'github-actions',
            language: 'node',
          },
        };
      }
      if (hasDocsPath) {
        return {
          actionId: 'docs.bootstrap@v1',
          suggestedInputs: {
            provider,
            owner,
            repo,
            entityId:  entity.id,
            docsPath:  'docs',
          },
        };
      }
      // Generic file creation for other anyOf paths
      return buildFileExistsFix(paths[0] ?? '', { provider, owner, repo, defaultBranch });
    }

    // entity.field.exists and entity.link.exists require human input — no auto fix
    case 'entity.field.exists':
    case 'entity.link.exists':
      return null;

    default:
      return null;
  }
}

function buildFileExistsFix(
  path: string,
  scm:  { provider: string; owner: string; repo: string; defaultBranch: string },
): FixActionSuggestion | null {
  if (!path || !scm.owner || !scm.repo) return null;

  const defaultContent = buildDefaultFileContent(path);
  if (!defaultContent) return null;

  return {
    actionId: 'scm.createOrUpdateFile@v1',
    suggestedInputs: {
      provider:      scm.provider,
      owner:         scm.owner,
      repo:          scm.repo,
      defaultBranch: scm.defaultBranch,
      path,
      contentBase64: Buffer.from(defaultContent).toString('base64'),
      message:       `[ForgePortal] Add ${path}`,
      branch:        `forge/fix-${path.replace(/[^a-z0-9]/gi, '-').toLowerCase()}`,
    },
  };
}

/**
 * Default file content templates for common missing files.
 * Returns null for unknown paths — only suggest fixes for files we know how to scaffold.
 */
function buildDefaultFileContent(path: string): string | null {
  if (path === 'README.md') {
    return `# Service

> Auto-generated by ForgePortal. Replace this with your service documentation.

## Overview

Describe what this service does.

## Getting Started

\`\`\`bash
# Add setup instructions here
\`\`\`

## Contact

Add owner information here.
`;
  }
  if (path === 'CONTRIBUTING.md') {
    return `# Contributing\n\nPlease read our team's contribution guidelines before submitting PRs.\n`;
  }
  if (path === 'CODEOWNERS') {
    return `# CODEOWNERS\n# Add ownership rules here, e.g.:\n# * @org/team-name\n`;
  }
  if (path === 'SECURITY.md') {
    return `# Security Policy\n\nTo report a security issue, contact the owning team directly.\n`;
  }
  // Unknown path — no template available
  return null;
}
