import { useState, useRef } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import { api } from '../../lib/api.js';

// ── Types ─────────────────────────────────────────────────────────────────────

type ScmProvider = 'github' | 'gitlab';

interface ScmForm {
  provider: ScmProvider;
  token:    string;
  org:      string;
  baseUrl:  string;
}

interface OidcForm {
  skip:         boolean;
  issuer:       string;
  clientId:     string;
  clientSecret: string;
}

interface PluginItem {
  id:      string;
  name?:   string;
  version?: string;
  status:  string;
}

interface ValidateScmResult {
  ok:     boolean;
  repos?: number;
  error?: string;
}

const TOTAL_STEPS = 3;

// ── Helpers ───────────────────────────────────────────────────────────────────

function generateYaml(
  scm: ScmForm,
  oidc: OidcForm,
  enabledPlugins: Set<string>,
): string {
  const lines: string[] = [
    '# Generated by ForgePortal Setup Wizard',
    '# Paste this into your forgeportal.yaml and restart the service.',
    '',
    'server:',
    '  port: 3000',
    '',
    'auth:',
    '  sessionSecret: "CHANGE_ME_TO_A_RANDOM_32_CHAR_STRING"',
  ];

  if (!oidc.skip) {
    lines.push('  oidc:');
    lines.push(`    issuer: "${oidc.issuer}"`);
    lines.push(`    clientId: "${oidc.clientId}"`);
    lines.push(`    clientSecret: "${oidc.clientSecret}"`);
  }

  lines.push('');
  lines.push('scm:');
  lines.push(`  - provider: ${scm.provider}`);
  lines.push(`    token: "${scm.token}"`);
  lines.push(`    org: "${scm.org}"`);
  if (scm.baseUrl) {
    lines.push(`    baseUrl: "${scm.baseUrl}"`);
  }

  if (enabledPlugins.size > 0) {
    lines.push('');
    lines.push('plugins:');
    for (const id of enabledPlugins) {
      lines.push(`  - id: ${id}`);
      lines.push('    enabled: true');
    }
  }

  lines.push('');
  lines.push('database:');
  lines.push('  url: "postgresql://forgeportal:forgeportal@localhost:5432/forgeportal"');

  return lines.join('\n');
}

// ── Sub-components ─────────────────────────────────────────────────────────────

function StepperDot({
  step, current, label,
}: { step: number; current: number; label: string }) {
  const done    = current > step;
  const active  = current === step;

  return (
    <div className="flex flex-col items-center gap-1.5">
      <div
        className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-semibold border-2 transition-colors ${
          done
            ? 'bg-indigo-600 border-indigo-600 text-white'
            : active
            ? 'border-indigo-600 text-indigo-600 bg-white'
            : 'border-gray-300 text-gray-400 bg-white'
        }`}
      >
        {done ? (
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
          </svg>
        ) : (
          step
        )}
      </div>
      <span className={`text-xs font-medium ${active ? 'text-indigo-700' : done ? 'text-gray-600' : 'text-gray-400'}`}>
        {label}
      </span>
    </div>
  );
}

function StepCard({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-gray-200 bg-white shadow-sm overflow-hidden">
      <div className="px-6 py-4 border-b border-gray-100">
        <h2 className="text-base font-semibold text-gray-900">{title}</h2>
      </div>
      <div className="px-6 py-5 space-y-4">{children}</div>
    </div>
  );
}

function FieldLabel({ children, required }: { children: React.ReactNode; required?: boolean }) {
  return (
    <label className="block text-sm font-medium text-gray-700">
      {children}
      {required && <span className="ml-1 text-red-500">*</span>}
    </label>
  );
}

function TextInput({
  value, onChange, placeholder, type = 'text',
}: {
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  type?: string;
}) {
  return (
    <input
      type={type}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      className="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 text-sm shadow-sm
                 placeholder-gray-400 focus:border-indigo-500 focus:ring-indigo-500 focus:outline-none"
    />
  );
}

// ── Step 1: SCM ───────────────────────────────────────────────────────────────

function StepScm({
  scm, setScm, onNext,
}: {
  scm: ScmForm;
  setScm: React.Dispatch<React.SetStateAction<ScmForm>>;
  onNext: () => void;
}) {
  const [result, setResult] = useState<ValidateScmResult | null>(null);

  const mutation = useMutation({
    mutationFn: () =>
      api.post<ValidateScmResult>('/admin/validate-scm', {
        provider: scm.provider,
        token:    scm.token,
        org:      scm.org,
        ...(scm.baseUrl ? { baseUrl: scm.baseUrl } : {}),
      }),
    onSuccess: (data) => setResult(data),
    onError: (err: unknown) => {
      const msg = err instanceof Error ? err.message : 'Connection failed';
      setResult({ ok: false, error: msg });
    },
  });

  const canTest  = scm.token.length > 0 && scm.org.length > 0;
  const canContinue = result?.ok === true;

  return (
    <StepCard title="Step 1 — Source Control Manager">
      {/* Provider */}
      <div>
        <FieldLabel required>Provider</FieldLabel>
        <div className="mt-2 flex gap-4">
          {(['github', 'gitlab'] as ScmProvider[]).map((p) => (
            <label key={p} className="flex items-center gap-2 cursor-pointer">
              <input
                type="radio"
                name="provider"
                value={p}
                checked={scm.provider === p}
                onChange={() => { setScm((s) => ({ ...s, provider: p })); setResult(null); }}
                className="text-indigo-600 focus:ring-indigo-500"
              />
              <span className="text-sm font-medium text-gray-700 capitalize">{p === 'github' ? 'GitHub' : 'GitLab'}</span>
            </label>
          ))}
        </div>
      </div>

      {/* Token */}
      <div>
        <FieldLabel required>Personal Access Token</FieldLabel>
        <TextInput
          type="password"
          value={scm.token}
          onChange={(v) => { setScm((s) => ({ ...s, token: v })); setResult(null); }}
          placeholder={scm.provider === 'github' ? 'ghp_…' : 'glpat-…'}
        />
        <p className="mt-1 text-xs text-gray-400">
          {scm.provider === 'github'
            ? 'Requires read:org and repo scopes.'
            : 'Requires read_api scope.'}
        </p>
      </div>

      {/* Org */}
      <div>
        <FieldLabel required>{scm.provider === 'github' ? 'GitHub Organisation' : 'GitLab Group'}</FieldLabel>
        <TextInput
          value={scm.org}
          onChange={(v) => { setScm((s) => ({ ...s, org: v })); setResult(null); }}
          placeholder={scm.provider === 'github' ? 'my-company' : 'my-group'}
        />
      </div>

      {/* Base URL (optional) */}
      <div>
        <FieldLabel>Base URL <span className="text-gray-400 font-normal">(optional — for GHES / self-hosted)</span></FieldLabel>
        <TextInput
          value={scm.baseUrl}
          onChange={(v) => { setScm((s) => ({ ...s, baseUrl: v })); setResult(null); }}
          placeholder={scm.provider === 'github' ? 'https://github.mycompany.com/api/v3' : 'https://gitlab.mycompany.com'}
        />
      </div>

      {/* Test connection */}
      <div className="flex items-center gap-3 pt-1">
        <button
          type="button"
          disabled={!canTest || mutation.isPending}
          onClick={() => mutation.mutate()}
          className="inline-flex items-center gap-1.5 rounded-md border border-gray-300 bg-white
                     px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50
                     disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          {mutation.isPending ? (
            <>
              <svg className="h-4 w-4 animate-spin text-gray-500" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Testing…
            </>
          ) : 'Test connection'}
        </button>

        {result && (
          result.ok ? (
            <span className="inline-flex items-center gap-1.5 rounded-full bg-green-50 px-3 py-1 text-xs font-medium text-green-700 border border-green-200">
              <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
              </svg>
              Connected — {result.repos ?? 0} repositories accessible
            </span>
          ) : (
            <span className="inline-flex items-center gap-1.5 rounded-full bg-red-50 px-3 py-1 text-xs font-medium text-red-700 border border-red-200">
              <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
              {result.error}
            </span>
          )
        )}
      </div>

      <div className="flex justify-end pt-2">
        <button
          type="button"
          disabled={!canContinue}
          onClick={onNext}
          className="rounded-md bg-indigo-600 px-5 py-2 text-sm font-semibold text-white
                     shadow-sm hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Continue →
        </button>
      </div>
    </StepCard>
  );
}

// ── Step 2: OIDC ──────────────────────────────────────────────────────────────

function StepOidc({
  oidc, setOidc, onNext, onBack,
}: {
  oidc: OidcForm;
  setOidc: React.Dispatch<React.SetStateAction<OidcForm>>;
  onNext: () => void;
  onBack: () => void;
}) {
  const filled = !oidc.skip && oidc.issuer && oidc.clientId && oidc.clientSecret;
  const canContinue = oidc.skip || Boolean(filled);

  return (
    <StepCard title="Step 2 — OIDC Authentication (optional)">
      <div className="rounded-lg border border-blue-100 bg-blue-50 px-4 py-3">
        <p className="text-sm text-blue-700">
          Skip this step to use <strong>dev mode</strong> — you will be auto-logged in as admin.
          Configure OIDC for production use.
        </p>
      </div>

      {/* Skip button */}
      <button
        type="button"
        onClick={() => { setOidc((o) => ({ ...o, skip: true })); onNext(); }}
        className="w-full rounded-md border border-gray-300 bg-white px-4 py-2.5 text-sm font-medium
                   text-gray-700 hover:bg-gray-50 transition-colors"
      >
        Skip — use dev mode (auto-login as admin)
      </button>

      <div className="relative flex items-center">
        <div className="flex-grow border-t border-gray-200" />
        <span className="mx-3 shrink text-xs text-gray-400">or configure OIDC</span>
        <div className="flex-grow border-t border-gray-200" />
      </div>

      {/* OIDC fields */}
      <div className={oidc.skip ? 'opacity-50 pointer-events-none space-y-4' : 'space-y-4'}>
        <div>
          <FieldLabel>OIDC Issuer URL</FieldLabel>
          <TextInput
            value={oidc.issuer}
            onChange={(v) => setOidc((o) => ({ ...o, issuer: v, skip: false }))}
            placeholder="https://auth.mycompany.com"
          />
        </div>
        <div>
          <FieldLabel>Client ID</FieldLabel>
          <TextInput
            value={oidc.clientId}
            onChange={(v) => setOidc((o) => ({ ...o, clientId: v, skip: false }))}
            placeholder="forgeportal"
          />
        </div>
        <div>
          <FieldLabel>Client Secret</FieldLabel>
          <TextInput
            type="password"
            value={oidc.clientSecret}
            onChange={(v) => setOidc((o) => ({ ...o, clientSecret: v, skip: false }))}
            placeholder="••••••••••••"
          />
        </div>
      </div>

      <div className="flex justify-between pt-2">
        <button
          type="button"
          onClick={onBack}
          className="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium
                     text-gray-700 hover:bg-gray-50 transition-colors"
        >
          ← Back
        </button>
        <button
          type="button"
          disabled={!canContinue}
          onClick={onNext}
          className="rounded-md bg-indigo-600 px-5 py-2 text-sm font-semibold text-white
                     shadow-sm hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Continue →
        </button>
      </div>
    </StepCard>
  );
}

// ── Step 3: Plugins ───────────────────────────────────────────────────────────

function StepPlugins({
  enabledPlugins, setEnabledPlugins, onNext, onBack,
}: {
  enabledPlugins: Set<string>;
  setEnabledPlugins: React.Dispatch<React.SetStateAction<Set<string>>>;
  onNext: () => void;
  onBack: () => void;
}) {
  const { data: pluginsData, isLoading } = useQuery({
    queryKey: ['admin-plugins'],
    queryFn:  () => api.get<PluginItem[]>('/plugins'),
  });

  const plugins = Array.isArray(pluginsData) ? pluginsData : [];

  const toggle = (id: string) => {
    setEnabledPlugins((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  return (
    <StepCard title="Step 3 — Plugins">
      <p className="text-sm text-gray-500">
        Enable or disable the plugins you want in your configuration. You can change this later from
        Admin → Plugins.
      </p>

      {isLoading ? (
        <div className="flex justify-center py-6">
          <svg className="h-6 w-6 animate-spin text-indigo-500" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
        </div>
      ) : plugins.length === 0 ? (
        <div className="rounded-lg border border-gray-100 bg-gray-50 px-4 py-4 text-sm text-gray-500">
          No plugins detected. Install plugin packages and restart to see them here.
        </div>
      ) : (
        <ul className="divide-y divide-gray-100 rounded-lg border border-gray-200">
          {plugins.map((p) => {
            const on = enabledPlugins.has(p.id);
            return (
              <li key={p.id} className="flex items-center justify-between px-4 py-3">
                <div>
                  <p className="text-sm font-medium text-gray-800">{p.name ?? p.id}</p>
                  {p.version && (
                    <p className="text-xs text-gray-400">v{p.version}</p>
                  )}
                </div>
                {/* Toggle */}
                <button
                  type="button"
                  role="switch"
                  aria-checked={on}
                  onClick={() => toggle(p.id)}
                  className={`relative inline-flex h-5 w-9 shrink-0 cursor-pointer rounded-full border-2 border-transparent
                              transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-1
                              ${on ? 'bg-indigo-600' : 'bg-gray-200'}`}
                >
                  <span
                    className={`pointer-events-none inline-block h-4 w-4 transform rounded-full bg-white shadow
                                ring-0 transition duration-200 ${on ? 'translate-x-4' : 'translate-x-0'}`}
                  />
                </button>
              </li>
            );
          })}
        </ul>
      )}

      <div className="flex justify-between pt-2">
        <button
          type="button"
          onClick={onBack}
          className="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium
                     text-gray-700 hover:bg-gray-50 transition-colors"
        >
          ← Back
        </button>
        <button
          type="button"
          onClick={onNext}
          className="rounded-md bg-indigo-600 px-5 py-2 text-sm font-semibold text-white
                     shadow-sm hover:bg-indigo-500"
        >
          Generate config →
        </button>
      </div>
    </StepCard>
  );
}

// ── Step 4: Summary ───────────────────────────────────────────────────────────

function StepSummary({
  scm, oidc, enabledPlugins, onBack,
}: {
  scm: ScmForm;
  oidc: OidcForm;
  enabledPlugins: Set<string>;
  onBack: () => void;
}) {
  const yaml = generateYaml(scm, oidc, enabledPlugins);
  const [copied, setCopied] = useState(false);
  const textRef = useRef<HTMLPreElement>(null);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(yaml);
    } catch {
      // fallback
      if (textRef.current) {
        const range = document.createRange();
        range.selectNode(textRef.current);
        window.getSelection()?.removeAllRanges();
        window.getSelection()?.addRange(range);
        document.execCommand('copy');
        window.getSelection()?.removeAllRanges();
      }
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <StepCard title="Your forgeportal.yaml">
      <div className="rounded-lg border border-green-200 bg-green-50 px-4 py-3">
        <p className="text-sm text-green-700">
          <strong>Almost there!</strong> Copy this configuration, paste it into your{' '}
          <code className="rounded bg-green-100 px-1 text-xs font-mono">forgeportal.yaml</code>,
          then restart the service.
        </p>
      </div>

      <div className="relative">
        <pre
          ref={textRef}
          className="overflow-x-auto rounded-lg bg-gray-900 p-4 text-xs text-green-300 font-mono leading-relaxed max-h-80"
        >
          {yaml}
        </pre>
        <button
          type="button"
          onClick={copy}
          className="absolute top-2 right-2 rounded-md bg-gray-700 px-2.5 py-1 text-xs font-medium
                     text-gray-200 hover:bg-gray-600 transition-colors"
        >
          {copied ? '✓ Copied!' : 'Copy'}
        </button>
      </div>

      <div className="rounded-lg border border-amber-100 bg-amber-50 px-4 py-3 text-xs text-amber-700">
        <strong>Note:</strong> Replace <code className="rounded bg-amber-100 px-1 font-mono">CHANGE_ME_TO_A_RANDOM_32_CHAR_STRING</code> with a
        secure random string before going to production. Store your token securely (e.g. via an
        environment variable or secret manager).
      </div>

      <div className="flex justify-between pt-2">
        <button
          type="button"
          onClick={onBack}
          className="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium
                     text-gray-700 hover:bg-gray-50 transition-colors"
        >
          ← Back
        </button>
        <button
          type="button"
          onClick={copy}
          className="rounded-md bg-indigo-600 px-5 py-2 text-sm font-semibold text-white
                     shadow-sm hover:bg-indigo-500"
        >
          {copied ? '✓ Copied to clipboard!' : 'Copy to clipboard'}
        </button>
      </div>
    </StepCard>
  );
}

// ── Main wizard page ───────────────────────────────────────────────────────────

const STEP_LABELS = ['SCM', 'OIDC', 'Plugins', 'Summary'];

export default function AdminSetupPage() {
  const [step, setStep] = useState(1);

  const [scm, setScm] = useState<ScmForm>({
    provider: 'github',
    token:    '',
    org:      '',
    baseUrl:  '',
  });

  const [oidc, setOidc] = useState<OidcForm>({
    skip:         true,
    issuer:       '',
    clientId:     '',
    clientSecret: '',
  });

  const [enabledPlugins, setEnabledPlugins] = useState<Set<string>>(new Set());

  const next = () => setStep((s) => Math.min(s + 1, TOTAL_STEPS + 1));
  const back = () => setStep((s) => Math.max(s - 1, 1));

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <h2 className="text-xl font-bold text-gray-900">Setup Wizard</h2>
        <p className="mt-1 text-sm text-gray-500">
          Configure ForgePortal in a few steps and generate your <code className="rounded bg-gray-100 px-1 font-mono text-xs">forgeportal.yaml</code>.
        </p>
      </div>

      {/* Stepper */}
      <div className="flex items-center gap-0">
        {STEP_LABELS.map((label, i) => {
          const s = i + 1;
          return (
            <div key={s} className="flex items-center flex-1">
              <StepperDot step={s} current={step} label={label} />
              {s < STEP_LABELS.length && (
                <div
                  className={`flex-1 h-px mx-1 transition-colors ${
                    step > s ? 'bg-indigo-400' : 'bg-gray-200'
                  }`}
                />
              )}
            </div>
          );
        })}
      </div>

      {/* Step content */}
      {step === 1 && (
        <StepScm scm={scm} setScm={setScm} onNext={next} />
      )}
      {step === 2 && (
        <StepOidc oidc={oidc} setOidc={setOidc} onNext={next} onBack={back} />
      )}
      {step === 3 && (
        <StepPlugins
          enabledPlugins={enabledPlugins}
          setEnabledPlugins={setEnabledPlugins}
          onNext={next}
          onBack={back}
        />
      )}
      {step === 4 && (
        <StepSummary
          scm={scm}
          oidc={oidc}
          enabledPlugins={enabledPlugins}
          onBack={back}
        />
      )}
    </div>
  );
}
